name       : password-store
version    : 1.6.5
release    : 2
source     :
    - http://git.zx2c4.com/password-store/snapshot/password-store-1.6.5.tar.xz : 337a39767e6a8e69b2bcc549f27ff3915efacea57e5334c6068fcb72331d7315
license    : GPL-2.0
component  : security
summary    : Stores, retrieves, generates, and synchronizes passwords securely.
description: |
    Stores, retrieves, generates, and synchronizes passwords securely.
rundeps  :
    - gnupg
    - pwgen
    - tree
    - xclip
install    : |
    %make_install FORCE_BASHCOMP=1 FORCE_ZSHCOMP=1 \
        BASHCOMP_PATH=%installroot%/usr/share/bash-completion/completions \
        ZSHCOMP_PATH=%installroot%/usr/share/zsh/site-functions
    install -Dm00755 $installdir/usr/bin/pass $installdir/usr/bin/password-store
    install -Dm000644 $installdir/usr/share/bash-completion/completions/pass \
        $installdir/usr/share/bash-completion/completions/password-store
    install -Dm000644 $installdir/usr/share/man/man1/pass.1 $installdir/usr/share/man/man1/password-store.1
    install -Dm000644 $installdir/usr/share/zsh/site-functions/_pass $installdir/usr/share/zsh/site-functions/_password-store

