name       : password-store
version    : 1.7.1
release    : 6
source     :
    - https://git.zx2c4.com/password-store/snapshot/password-store-1.7.1.tar.xz : f6d2199593398aaefeaa55e21daddfb7f1073e9e096af6d887126141e99d9869
license    : GPL-2.0
component  : security
summary    : Stores, retrieves, generates, and synchronizes passwords securely.
description: |
    Stores, retrieves, generates, and synchronizes passwords securely.
rundeps    :
    - qrencode
    - gnupg
    - tree
    - xclip
install    : |
    %make_install FORCE_BASHCOMP=1 FORCE_ZSHCOMP=1 \
        BASHCOMP_PATH=%installroot%/usr/share/bash-completion/completions \
        ZSHCOMP_PATH=%installroot%/usr/share/zsh/site-functions
    install -Dm00755 $installdir/usr/bin/pass $installdir/usr/bin/password-store
    install -Dm000644 $installdir/usr/share/bash-completion/completions/pass \
        $installdir/usr/share/bash-completion/completions/password-store
    install -Dm000644 $installdir/usr/share/man/man1/pass.1 $installdir/usr/share/man/man1/password-store.1
    install -Dm000644 $installdir/usr/share/zsh/site-functions/_pass $installdir/usr/share/zsh/site-functions/_password-store
    install -Dm000755 contrib/dmenu/passmenu $installdir/usr/bin/passmenu

