name       : password-store
version    : 1.6.5
release    : 1
source     :
    - http://git.zx2c4.com/password-store/snapshot/password-store-1.6.5.tar.xz : 337a39767e6a8e69b2bcc549f27ff3915efacea57e5334c6068fcb72331d7315
license    : GPL-2.0
summary    : Stores, retrieves, generates, and synchronizes passwords securely.
description: |
    Stores, retrieves, generates, and synchronizes passwords securely.
rundeps  :
    - gnupg
    - pwgen
    - tree
    - xclip
install    : |
    mkdir -p %installroot%/usr/share/bash-completion/completions/
    mkdir -p %installroot%/usr/share/zsh/site-functions/
    %make_install FORCE_BASHCOMP=1 FORCE_ZSHCOMP=1 \
        BASHCOMP_PATH=%installroot%/usr/share/bash-completion/completions \
        ZSHCOMP_PATH=%installroot%/usr/share/zsh/site-functions
    mv %installroot%/usr/bin/pass %installroot%/usr/bin/password-store
    mv %installroot%/usr/share/bash-completion/completions/pass \
        %installroot%/usr/share/bash-completion/completions/password-store
    mv %installroot%/usr/share/man/man1/pass.1 %installroot%/usr/share/man/man1/password-store.1
    mv %installroot%/usr/share/zsh/site-functions/_pass %installroot%/usr/share/zsh/site-functions/_password-store

